name: VhostGuard
version: ${version}
main: com.vhostguard.VhostGuard
api-version: '1.21'
load: STARTUP
description: Kick logins that do not use an allowed hostname.
author: VhostGuard
website: https://github.com/sprakilesisgood/vhost-guard
libraries:
  - com.google.code.gson:gson:${gson_version}
